# Generated by Django 5.0.2 on 2024-06-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
